version: '3.9'

services:

  backend:
    build: ../backend
    ports:
      - "8000:8000"

  frontend:
    build: ../frontend
    ports:
      - "5173:5173"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"